### ISSUE TITLE
Bring back SpreadsheetView and TableView2

### ISSUE THREAD

**Issue by abhinayagarwal** [controlsfx/controlsfx#1141]
In JavaFX 9, VirtualFlow was no longer accessible. Controls like `SpreadsheetView and `TableView2` could no longer run on JavaFX 9 and above.

However, this changed in JavaFX 12 with [JDK-8207942](https://bugs.openjdk.java.net/browse/JDK-8207942). We can now bring back both the controls for ControlsFX 12.0.0 release.

For now, I would prefer them to be added to a new branch forked out of existing `9.0.0` branch.

**Comment by wirew0rm** [comment]
I tried to work on this because we are in the process of migrating a project which uses SpreadsheetView from java8 to openjdk11+JavaFX.

I've started by importing the relevant files (only for SpreadsheetView for now) from master into a new branch branched from 9.0.0 and trying to fix issues by looking at the "Update * to make it compatible with JavaFX 9" commits.
This discussion of this topic on [bitbucket](https://bitbucket.org/controlsfx/controlsfx/issues/780/controlsfx-should-support-java-9#comment-42691047) also mentions that a lot of other internal APIs have changed and have to be adapted.

Unfortunately I was not able to properly import the project into eclipse (#937 ) so this has been going very slow. Any pointers there would be much appreciated.

**Comment by Maxoudela** [comment]
FYI, I'm targeting a compatible SpreadsheetView with OpenJFX 13 (that could use OpenJDK 11 LTS). As of OpenJFX 12, I think we are still missing some things.

My main concern is to push all the things I need into OpenJFX 13 (still some PR hanging), then I'll make the change in ControlsFX, preferably in another branch.

**Comment by abhinayagarwal** [comment]
@Maxoudela That sounds great :+1: 

Keep us updated.

**Comment by InnaB** [comment]
Are there any news? We are switching to java11 and this is a real showstopper. The FilteredTableView is amazing and we hope to keep using it.
Or are there at least any workarounds in the meantime?
Thank you for all the work!

**Comment by Maxoudela** [comment]
We could attempt to bring them back into ControlsFX. @abhinayagarwal  What are you suggestion? I would suggest having a new branch using OpenJFX 13 and I could push a compatible SpreadsheetView (maybe with some limitations).

**Comment by abhinayagarwal** [comment]
@Maxoudela Sounds good!

**Comment by InnaB** [comment]
Thank You :)

**Comment by Maxoudela** [comment]
@abhinayagarwal Could you help me on that? I'm quite a noob when it comes to Gradle or Github. Should we create a 13.0 branch that is an exact copy of the 9.0.0 branch but only with the OpenJFX changing to 13 and OpenJDK to 13?

**Comment by abhinayagarwal** [comment]
@Maxoudela I have pushed a new branch `jfx-13` to ControlsFX. It uses OpenJFX 13.

**Comment by Maxoudela** [comment]
Allright thanks! I have  fetch your branch and built it using JDK 13.

I have committed an early version of the SpreadsheetView in my local branch : https://github.com/Maxoudela/controlsfx/commit/697d9eacfb523056befcb458624303a3530034e9

I did add this in gradle :
```
//For SpreadsheetView
        "--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior.TableViewBehavior=org.controlsfx.controls",
        //For SpreadsheetView
        "--add-exports=javafx.base/com.sun.javafx.event.EventHandlerManager=org.controlsfx.controls"
```

Is this normal/allowed?

Also I did need to modify Translations.java as FileSystems.newFileSystem has two constructors now (maybe because I used JDK 13 instead of JDK 11?).

My current changes are loaded with new features that I have not pushed to ControlsFX 8. I'll make a pull request for JDK 8 first, then I'll update my 13 branch accordingly and make a pull request for 13 branch.

**Comment by Maxoudela** [comment]
@cliviu Which branch did you actually tried? This one: https://github.com/controlsfx/controlsfx/tree/jfx-13 or this one : https://github.com/Maxoudela/controlsfx/tree/jfx-13 ?

Can you check the solution provided here : https://stackoverflow.com/questions/54291958/javafx-11-illegalaccesserror-when-creating-label
 Did you properly add the required modules to run the whole thing?

**Comment by cliviu** [comment]
@Maxoudela I have tried with your fork https://github.com/Maxoudela/controlsfx/tree/jfx-13 because I need the SpreadsheetView. 
 Regarding the required modules, my Vm arguments line looks like this : --module-path /..path..to/javafx-sdk-13.0.1/lib --add-modules javafx.controls,javafx.fxml,javafx.media,javafx.web,javafx.base,javafx.graphics

**Comment by cliviu** [comment]
why is it "unnamed" module  ?

**Comment by Maxoudela** [comment]
I'm trying to run it through IntelliJ but I'm not able to do so. I'm so annoyed by that, I feel like I need 2 hours each time to make everything run smoothly again. 

I'll let myself some things in case I stumble accross these issues again:
Allright, I've been able to open the root ControlsFX project by selecting the gradle file otherwise it would do nothing

Then I add an @Ignore on JavaFXThreadingRule otherwise it would complain.

In Edit configuration, I add that indeed : `--module-path "C:\Program Files\Java\javafx-sdk-13.0.1\lib" --add-modules javafx.controls,javafx.media,javafx.web,javafx.base,javafx.graphics`

Be sure to remove the space after the comma because otherwise it complains!

Now I have : 
`Caused by: java.lang.IllegalAccessException: class com.sun.javafx.application.LauncherImpl (in module javafx.graphics) cannot access class org.controlsfx.samples.spreadsheet.HelloSpreadsheetView (in module org.controlsfx.samples) because module org.controlsfx.samples does not export org.controlsfx.samples.spreadsheet to module javafx.graphics`

**Comment by cliviu** [comment]
ok thanks. Can you start it with Eclipse ?

**Comment by yuliu2016** [comment]
I've been able to use the fork at https://github.com/Maxoudela/controlsfx/tree/jfx-13. `SpreadsheetView` requires an internal API that can only be exposed via a few extra command-line arguments:
```
--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls
--add-exports=javafx.base/com.sun.javafx.event=org.controlsfx.controls
--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls
--add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls
```
Adding these four options to the VM should fix the `IllegalAccessError` above and make the `SpreadsheetView` function correctly

**Comment by cliviu** [comment]
@yuliu2016 , can you please post your complete VM options line ?  I still have the same problems running my application. Thanks !

**Comment by yuliu2016** [comment]
I use Gradle which manages the VM options for me. All I did was appending those options and Gradle gives me something like this: https://pastebin.com/fXKQT1MF. I don't think that's particularly helpful. 

What is your specific problem? Is it still the `IllegalAccessError`? Can you post what your VM options?

**Comment by cliviu** [comment]
My VM options  : `--module-path /path..to/javafx-sdk-13.0.1/lib --add-modules javafx.controls,javafx.fxml,javafx.media,javafx.web,javafx.base,javafx.graphics --add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls --add-exports=javafx.base/com.sun.javafx.event=org.controlsfx.controls --add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls --add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls`  . I still have the same `IllegalAccessError` 
In the --module-path location I have :
controlsfx-12.0.0-SNAPSHOT.jar
javafx.base.jar
javafx.controls.jar
javafx.fxml.jar
javafx.graphics.jar
javafx.media.jar
javafx.swing.jar
javafx-swt.jar
javafx.web.jar

**Comment by cliviu** [comment]
If I add org.controlsfx.controls to the modules  `--add-modules org.controlsfx.controls,javafx.controls,javafx.fxml,javafx.media,javafx.web,javafx.base,javafx.graphics ` 
I get this Exception : 

Caused by: java.lang.IllegalAccessException: class javafx.fxml.FXMLLoader$InstanceDeclarationElement (in module javafx.fxml) cannot access class impl.org.controlsfx.skin.DecorationPane (in module org.controlsfx.controls) because module org.controlsfx.controls does not export impl.org.controlsfx.skin to module javafx.fxml

**Comment by yuliu2016** [comment]
You did it right the second time. Your exception is now a different problem. The problem is that DecorationPane is an internal API that is not exported to other modules here https://github.com/Maxoudela/controlsfx/blob/jfx-13/controlsfx/src/main/java/module-info.java

One way to fix this is to add yet another option to the VM so that FXML can instantiate it:
`--add-exports=org.controlsfx.controls/impl.org.controlsfx.skin=javafx.fxml` But there must be a reason that it's made private. Could you use a public API like `Decorator` instead?

Also if you are using anything other than SpreadsheetView there is a list of options here that you can add if you get IllegalAccessErrors: https://github.com/controlsfx/controlsfx/blob/4ce2a7d848de6734c7e78ff00f766d3ec7fa9d2a/build.gradle#L13-L33

**Comment by cliviu** [comment]
@yuliu2016 , thanks ! I will try it on Monday

**Comment by cliviu** [comment]
@yuliu2016, Thanks, I have tried and I can start my Application. I still have some problem, the view looks a bit different, there is some space left between the lines ..
Here it is java 8
![spreadsheet_java8](https://user-images.githubusercontent.com/2623175/68092610-62074c00-fe8d-11e9-993a-5cb747d46a3f.png)
Here it is java 11 
![spreadsheet_java11](https://user-images.githubusercontent.com/2623175/68092621-764b4900-fe8d-11e9-8c4d-7bc7fb8d320e.png)

**Comment by Maxoudela** [comment]
> 
> 
> I've been able to use the fork at https://github.com/Maxoudela/controlsfx/tree/jfx-13. `SpreadsheetView` requires an internal API that can only be exposed via a few extra command-line arguments:
> 
> ```
> --add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls
> --add-exports=javafx.base/com.sun.javafx.event=org.controlsfx.controls
> --add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls
> --add-opens=javafx.graphics/javafx.scene=org.controlsfx.controls
> ```
> 
> Adding these four options to the VM should fix the `IllegalAccessError` above and make the `SpreadsheetView` function correctly

Allright thanks a lot! I've added that and managed to run HelloSpreadsheetView and HelloSpreadsheetView2. Could we put these option into the module info somehow or it can only be put in the command line?

@cliviu This branch is simply a working SpreadsheetView. I have deactivated many things, I'm waiting that we merge #1194 first in master, then I'll merge the JFX13 for initial commit and we will start fixing what I have deactivated.

**Comment by yuliu2016** [comment]
As far as I know, they have to be on the command line to work. The only other way I can think of is somehow modifying the module-info class of the JavaFX artifact jars itself, which doesn't seem reasonable. 

Just curious, what kind of things did you deactivate in the SpreadsheetView?

**Comment by Maxoudela** [comment]
@yuliu2016 What I have deactivated can be seen (among others) in `FIXME` in the code.

I have mostly commented specific lines that are not in the API anymore. I don't measure the impact yet (`cell.impl_processCSS(false); col.impl_setWidth(widthMax);`)

Also the `resizeColumnToFitContent` is not implemented, I'm trying to push it into OpenJFX 14. The feature when all selected columns are resized has been deactivated in `HorizontalHeaderColum`n line 70

In `GridRowSkin`, we had `handleControlPropertyChanged(String p)` as a method but it has changed.

So I think the whole thing is working but we may experience some bugs that will need to be investigated and fixed.

**Comment by cliviu** [comment]
> If you guys are using the SpreadsheetView and want to be involved, I encourage you to review my JDK8 pull request here : #1194.
I'm not sure if I'm entitled to review that ...
From the screenshot that I've sent you it looks like the row height has some problems currently ...

**Comment by Maxoudela** [comment]
> 
> 
> > If you guys are using the SpreadsheetView and want to be involved, I encourage you to review my JDK8 pull request here : #1194.
> 
> I'm not sure if I'm entitled to review that ...
> From the screenshot that I've sent you it looks like the row height has some problems currently ...

Anyone can review, any remarks is welcomed!
Regarding the row height, I think it may be linked with the things I deactivated in GridRowSkin. But I would like to first merge my code into JFX13, then we could open some issues and work on them. 

But if you have a [SSCCE](http://sscce.org/) that demonstrates the row height problem, you can still open an issue on my fork so that I start investigate it before merging my code into ControlsFX JFX13 branch

**Comment by cliviu** [comment]
> But if you have a [SSCCE](http://sscce.org/) that demonstrates the row height problem, you can still open an issue on my fork so that I start investigate it before merging my code into ControlsFX JFX13 branch
Do you mean that in your tests the SpreadsheetView looks the same as before  ?

**Comment by Maxoudela** [comment]
> 
> 
> > But if you have a [SSCCE](http://sscce.org/) that demonstrates the row height problem, you can still open an issue on my fork so that I start investigate it before merging my code into ControlsFX JFX13 branch
> 
> Do you mean that in your tests the SpreadsheetView looks the same as before ?

I have ran the sampler and it seems fine. I'm now running it against my main application so I'm expecting to find some issues in the next few days. 

If you want to report a bug, report it in this tracker or on the pull request itself. I've seen that I don't have an issue tracker on my repository

**Comment by cliviu** [comment]
ok, I will take a look if I can make a simple program to reproduce the issue

**Comment by Groostav** [comment]
@Maxoudela I checked out [Maxoulda/controlsfx/jfx-13#61503fe7](https://github.com/Maxoudela/controlsfx/commit/7281600d13b8d0f601451f80f2215e9f61503fe7), and built it & deployed it on my app. After some wrangling with unrelated parts of java fx + java 13, I was able to get my legacy app, which makes heavy use of `SpreadsheetView`s, running on java 13. 

Once your commit there makes it into master here I'll likely be able to call my update from java 8 to java 13 done. 

Thank you so much for your hard work here. This is a boon for my codebase.

**Comment by cliviu** [comment]
> I have ran the sampler and it seems fine. I'm now running it against my main application so I'm expecting to find some issues in the next few days.
I have found the problem, it was somewhere in my css. Thank you very much for your help !

**Comment by Maxoudela** [comment]
I'm happy it's working for you.

I have integrated the SpreadsheetView within my main application. I've ran all the tests, find some minor regressions that I've fixed in the code.

I think it's safe to say that the SpreadsheetView is functional with JDK 13. We'll try to merge that as soon as possible. 
In the meantime, if you find some issues or regression, don't hesitate to open new issues.

**Comment by cliviu** [comment]
> I'm happy it's working for you.

Thank you very much for your efforts. Please let me know when there will be an official product..

**Comment by yuliu2016** [comment]
I've been using it for some more time, and everything seems to work well. I was able to:
- Create large spreadsheets, like with 18 columns and 7687 rows
- Apply an old stylesheet from java 8 with minimal changes
- Use all the features from the old project

But I have noticed a few very minor things. The selection rectangle is not always placed on the border of a cell when running on a high dpi computer screen. If I run it in a 100% scale screen it aligns perfectly, but on my laptop, which is 125% scale, I get something like this, where the vertical borders are not aligned:
![image](https://user-images.githubusercontent.com/22801773/69908067-f9d65800-13af-11ea-8e82-9e3addb7a8e6.png)
I think I have also seen some inconsistencies where the column width is resized automatically, but not correctly, leaving some cells with an ellipsis. I can't reproduce this right now, but I will post if I see it again.

Overall this has been great. Is there anything preventing this from being merged at this time? I know you said that you wanted to merge #1194 first, but there seems to be no recent activity there.

**Comment by Maxoudela** [comment]
Thanks for the feedback.

I know I have some issues on this rectangle, it's a bit messy sometimes. I could try to reproduce since I do have a high DPI screen at work.

For the column, it may be due to the autofit. Don't hesitate to open issues if you have a way to reproduce.

I'm waiting for a review before merging. I know that the SpreadsheetView is a bit big. I also know that I have introduce some features (Richtext cell) that may confuse people. If you would want to take a look at my PR, that would be great and ease the merge process as someone would have, at least, overlook what I did :)

PS: I'll be off for two weeks starting now

**Comment by cliviu** [comment]
Hi, any news on that ? is the merge already done ?

**Comment by Maxoudela** [comment]
Nope.. The PR is still there : https://github.com/controlsfx/controlsfx/pull/1210

It's kind of a big PR and I believe no one wants to review it (and I understand it^^)

I think we should merge them and then process the bugs as they come. Otherwise we will be stuck with the PR hanging for a while..

**Comment by abhinayagarwal** [comment]
@Maxoudela Sounds good to me. Lets merge the PR.

**Comment by Maxoudela** [comment]
@abhinayagarwal Should I merge both of them then?

**Comment by abhinayagarwal** [comment]
#1210 should be good to merge as it targets a new branch and has minimal impact.

I am not so sure about #1194 though as it targets master. I will try to review it soon.

**Comment by Maxoudela** [comment]
Allright, thanks, I have merged #1210 !

**Comment by cliviu** [comment]
Thank you guys so much that you are going forward with this issue ! When is the next release planned ? I mean an official product in maven central ?

**Comment by Maxoudela** [comment]
I do not know when the official release will take place. I know that we wanted to release more often as we suggested in #1220

**Comment by abhinayagarwal** [comment]
Release planning is more difficult than it was. Now, we have `jfx-13` branch, which will only work with JavaFX 13 and later. We already release from master, 9.0.0 branches as 8.x and 11.x respectively. Should we add ControlsFX 13.x to the existing version of releases?

I do not want to follow the Java/FX release cycle as that would mean updating the major release version every 6 months.

**Comment by Maxoudela** [comment]
I think it can be good to have a 13 release that indeed includes the SpreadsheetView. 

I was thinking to have a branch always on sync with the current Java release but it seems like a lot of work from what you are saying.

I know I'm waiting some new fix for SpreadsheetView on JDK 14. The best would be to have the 8.0, the 11.0 and another branch that is on sync with the latest release. But I honestly don't know how complicate and difficult that is.

**Comment by danielpeintner** [comment]
> The best would be to have the 8.0, the 11.0 and another branch that is on sync with the latest release.

I agree and it matches what others do (i.e., [AdoptOpenJDK](https://adoptopenjdk.net/))
Having said that, I see the the troubles keeping 3 branches in sync though...

**Comment by cliviu** [comment]
Hey guys, any news about a 13 Release with the SpreadsheetView ?

**Comment by Maxoudela** [comment]
FYI , I just merged #1194 so that both branch are in sync now. That's better for me to investigate on SpreadsheetView bugs.

@abhinayagarwal What do you think? Could we try to release something in the upcoming months? JavaFX14 has been released so I could rename the jfx-13 branch and update it. I don't know how you work with master and 9.0.0 branch? Do you merge all master commit into 9.0.0?

**Comment by abhinayagarwal** [comment]
Yes, all commits from master are merged into 9.0.0 to keep it up-to date with all changes made to master. It simply a matter of executing the following commands:

```
git checkout 9.0.0
git merge master
```
If there are any conflicts, fix them and make another commit.

I have been wanting to fork out master branch as a read-only branch and promote 9.0.0 to master. Do you think its ripe time to do so? Or, are there still many users on JavaFX 8 and we should keep supporting it as our main branch for now?

**Comment by Maxoudela** [comment]
Allright, do you want me to try updating the 9.0.0 branch and jfx-13 in sync with master?
I guess that some specific fix on 8.0 should not be merged into 9.0.0, I'll see if I can cherry pick the commits. 

> I have been wanting to fork out master branch as a read-only branch and promote 9.0.0 to master. Do you think its ripe time to do so? Or, are there still many users on JavaFX 8 and we should keep supporting it as our main branch for now?

Definitely a good question. Promoting 9.0.0 to master seems pretty fair. Read-only for 8.0.0 is maybe a bit extreme? We good decide to merge some issues that are discovered and are very annoying. But maybe they will be none. 
From my point of view, I'm still on Java 8 in my company. I think we will switch to OpenJDK 11 and OpenJFX 14 later on this year.

**Comment by abhinayagarwal** [comment]
@Maxoudela It will be easier for you to merge master -> 9.0.0. Then merge 9.0.0 -> jfx-13, as the latter was forked out of 9.0.0.

**Comment by abhinayagarwal** [comment]
On a second thought merging 9.0.0 to jfx-13 might not be a good idea as it won't have all the changes you did to SpreadSheetView in master.

**Comment by Maxoudela** [comment]
jfx-13 branch is in sync with master regarding SpreadsheetView I think. I'll try my best on monday and see what is the result :)

**Comment by gchariharan** [comment]
Hello guys, any updates on the release which include SpreadsheetView?

**Comment by Groostav** [comment]
@gchariharan @Maxoudela bump? i just merged my build of jfx-13 branch into my own repo's master, but I'd really rather have a published maven artifact from you.

**Comment by aaroncarlfernandez** [comment]
Hi everyone, if I am following the updates correctly, the SpreadsheetView can only be used from JDK 13 and not JDK 12? Thanks!

**Comment by yuliu2016** [comment]
> Hi everyone, if I am following the updates correctly, the SpreadsheetView can only be used from JDK 13 and not JDK 12? Thanks!

It is only compatible with JavaFX 13 (and 14, now that it's released). As far as I know, they are both compatible with JDK 11.

**Comment by Arthurm1** [comment]
Hi.  I imagine a full release takes someone a lot of time and energy.  In the mean time - would it be possible to add the `jdk-13` branch to `travis.yaml` so that we could have a snapshot release to build and test against?  Or is this also a lot of work - I'm not that familiar with Travis.

**Comment by abhinayagarwal** [comment]
Hi @Arthurm1,

Not a lot of work. This is just delayed because we are unable to decide what version it should be released under:

1. ControlsFX 13.0.0
2. ControlsFX 11.13.0

I am a little hesitant to make ControlsFX versioning follow JavaFX versioning as we might not have many changes for a major release.

**Comment by Arthurm1** [comment]
@abhinayagarwal  Understood - thanks for the update.  Don't suppose you could post the jar for jdk-13 (regardless of name) somewhere (on this issue possibly) so I could test against it?  I'm having trouble building it locally for some reason.

**Comment by abhinayagarwal** [comment]
We released 11.0.2 today 🎉 

Will try to identify the best way to release jfx-13 moving forward after I have reviewed #1280

**Comment by yuliu2016** [comment]
I was able to build https://github.com/Maxoudela/controlsfx/tree/jfx-13 after a few changes - it turns out that JavaFX `12.0.0`, the version used in `build.gradle`, doesn't actually exist. I changed it to `14.0.1`, the latest JavaFX version. There was also an unresolved and unused import to `javafx.scene.web.WebView` in `CellGraphicFactory`. I removed it. Then it built successfully.

Here's the snapshot jar (GitHub doesn't allow jar files here so I added `.zip`, just remove the extension): [controlsfx-14.0.1-SNAPSHOT.jar.zip](https://github.com/controlsfx/controlsfx/files/4848737/controlsfx-14.0.1-SNAPSHOT.jar.zip). I haven't tested with my projects, but the sample application w/ spreadsheet view seems to work.

**Comment by Maxoudela** [comment]
Thanks @yuliu2016 , I'll try to push these modifications to #1280 as I really suck on these Gradle things.

**Comment by cliviu** [comment]
hi, any news regarding the jfx-13 release ? Thanks !

**Comment by cliviu** [comment]
no news ?

**Comment by Maxoudela** [comment]
Hello

I tried to catch up the modification in #1280 but it wasn't really working though.

As you may have noticed, I'm super busy on other projects right now and I have literally no time for ControlsFX. Especially since I had great issues on building the whole thing up with IntelliJ. I always ended using the bad JDK and it drives me crazy. 

Long story short, I'll gladly help anyone who wants to take the lead on this subject but right now I have no bandwidth...

**Comment by cliviu** [comment]
hi @Maxoudela, What do you mean by taking the lead on this subject ?

**Comment by Maxoudela** [comment]
Hi,

The merge has been done so we only need to decide how we want it to be built. The main issue is that building and releasing a version built on branch `jfx-13` takes time and it means we should support it. Maybe we could drop the support of Java 8.0 and base our `master` branch on latest JDK-15 for example that would allow the modifications made on the SpreadsheetView to be on.

Temporarily, could you not build the branch on your side till we figure something?

**Comment by cliviu** [comment]
Sure, I understand that there is effort related with the maintaing of the branch. 

My problem is that I have built some fancy view with controlsfx for jfx8 using the SpreadsheetView and after  our framework was upgraded to JavaFX11 the Spreadsheet view from Controlsfx was gone.  

I was waiting for more than one and a half years for that view to come in the JavaFX11 version but now the delivery time has come and we should use only released software.  Not sure how to go on because I do not know how long it will take for the SpreadsheetView to be integrated  to the JavaFX11 branch.  Otherwise I will maybe have to reduce the functionality of my view and try to build myself some functionality using the plain JavaFX table. 

Let me know if I can somehow help to speed  the process of integrating the SpreadsheetView on the Java11 branch. Thanks !

**Comment by Maxoudela** [comment]
The SpreadsheetView will not work on JavaFX 11 since some API were not available. Right now, the SpreadsheetView can work using OpenJFX 13 and later, and Java JDK 11 and later.

I suggest talking with @abhinayagarwal in order to see what are our plans for the future. Our branch `9.0.0` is a bit outdated now so maybe it is the time to move `master` branch to the latest OpenJFX version and Java JDK version, and let the 8.0 version behind.

**Comment by cliviu** [comment]
Thanks @Maxoudela , @abhinayagarwal  , what are your plans for future regarding the latest OpenJFX Version and the SpreadsheetView  ?

**Comment by abhinayagarwal** [comment]
I am in support of @Maxoudela suggestion here. We have been planning to upgrade jfx-13 to master and leave behind JDK 8 for sometime now.

I do not want to just rename the branches as that will break it for everyone who has forked out the repository.

May be something inline with [this SO answer](https://stackoverflow.com/a/2763118) will work, but no sure. If anyone, who is better accustomed to GIT than I am, has a better idea; please feel free to write down your suggestions.

**Comment by Groostav** [comment]
So my understanding @Maxoudela is the work that needs to be done is entirely in CI configuration and gradle build config?

I wish I could help with Travis but I'm a teamcity guy and I'd like to help with your build system _but I really don't like gradle_. 

A couple other opinions nobody asked for:
1. delete `master` (or leave it where it is) and change the repo's default branch to `jfx-14` (or the most recent `jfx-X` branch), and update CI such that it checks out a specific branch. 
2. version this as `controlsfx-13.0.0`. Given that this code requires jfx-13 and cannot be run on jfx-11, calling it `11.13` would be confusing to me. As you go forward and add features to controlsfx, just increment the minor version. If open-jfx releases at version 16, and you guys add some new component/control that works as far back as open-jfx-13, release it as controlsfx-13.1.0. I think this is the simplest interpretation of semantic versioning for your project. 

Really looking forward to this! The spreadsheet view is a _vastly_ better component than TableView!

**Comment by abhinayagarwal** [comment]
Hi @Groostav,

Thank you for the feedback.

1. Changing the default branch to jfx-13 is another great option, this will save us from much of the headache.
2. My take on 11.13 was 11 would stand for Java version, 13 for JavaFX version and then any new release we do would go with 11.13.x. We need to break out of JavaFX release chain someday. However, since most people want 13.x.x, I guess that is where we should go :)

**Comment by abhinayagarwal** [comment]
Hi @cliviu ,

Please test `11.1.0-SNAPSHOT` with JavaFX 13 or later. It contains `SpreadsheetView`.

**Comment by cliviu** [comment]
hi @abhinayagarwal , thank you for taking care of the new version. I've made a smoke test with the Spreadsheet View, it looks good !

**Comment by danielpeintner** [comment]
Question: is there anything that holds back TableView2 reintegration?

What is the desired approach to bring back the work done by @jperedadnr ([here](https://github.com/controlsfx/controlsfx/commit/478004b9936f62b198b7ceab1f4071bc4c5d0cff))

**Comment by abhinayagarwal** [comment]
Hi @danielpeintner ,

It should be a matter of copying back the classes, fix all the imports, and then fix compatibility issues, if any.

**Comment by danielpeintner** [comment]
> It should be a matter of copying back the classes, fix all the imports, and then fix compatibility issues, if any.

I can do that and provide a PR for branch `jfx-13`, right?

The reasons why I asked in the first place is that in the end it would look like *my* contribution while it is work done by  @jperedadnr / Gluon.

Please let me know whether I should work on the PR or we wait for @jperedadnr to do it.

**Comment by danielpeintner** [comment]
FYI: I tried to copy over the source files and to me it looks **far** from just fixing imports.
Moreover, there seem to be still variables/methods that are internal and cannot be overridden or retrieved.

**Comment by jperedadnr** [comment]
I've found some time to check out the changes I did to TableView2 while testing [JDK-8207942](https://bugs.openjdk.java.net/browse/JDK-8207942) in OpenJFX 12 a while back.

As a result, I've created this PR: https://github.com/controlsfx/controlsfx/pull/1328, that brings back TableView2 control and restores the two related samples.

**Comment by abhinayagarwal** [comment]
Both the controls are now integrated to jfx-13 branch. Thanks to the great work from @Maxoudela and @jperedadnr .

These controls are currently available as snapshot builds in 11.1.0-SNAPSHOT. Will plan a release soon.

**Comment by HamidShaikh1499** [comment]
thanks to all developer 🎉😄 to resolve both controls and please update it...!

**Comment by HamidShaikh1499** [comment]
First of all thanks for bringing back those two controls of controlsfx and i am new in javafx and i need to use spreadsheetview component to open excel file instead of tableView so any one mind telling me when controlsfx 11.1.0-SNAPSHOT will be released?

**Comment by cliviu** [comment]
Hey, any news about the release of the 11.1.0 ?

**Comment by HamidShaikh1499** [comment]
@cliviu I check it in github daily so they update controlsfx controls only nowadays. And didn't release new version of controlsfx and i have been also waiting for this version for spreadsheet. if i would get any news so i will share it and if you would get news so please share it bro!

**Comment by abhinayagarwal** [comment]
v11.1.0 is now available

**Comment by cliviu** [comment]
> v11.1.0 is now available and contains both SpreadsheetView & TableView2.

Thank you all !
