### ISSUE TITLE
TableView, TableView2 and SpreadSheet all exhibit highly eratic scrollbar behavior

### ISSUE THREAD

**Issue by jcschatzman** [controlsfx/controlsfx#1372]
It appears that each of TableView, TableView2 and SpreadSheet  do not interact correctly with ScrollPane. When there is a large range of row heights this is very evident with the vertical scrollbar. Dragging the scrollbar tab up and down causes crazily drunken behavior with the scrollbar button size and position jumping up and down dramatically. Tiny motions of the scrollbar button cause huge changes in the display. Occasionally, the cell backgrounds and the cell text become unaligned, but this is not the most obvious problem.

I note that all the "controlsfx-samples" code has row vertical heights that vary only by at most a factor of 2-3, at which the issue is not very noticeable.  Increasing the variability to 40-to-1 or so makes this problem very evident.

**Comment by jcschatzman** [comment]
I have the impression that there are at least two different calculations going on:
a) One having to do with the number of rows visible in the viewport.
b) One with the number of pixels visible in the viewport.
And when the scrollbar is manipulated by the user, the code appears to bounce back and forth between the two calculations. When the rows all have about the same height, there is not much difference. When the row heights vary greatly, then the two calculations give very different results.

In the display I am looking at right now, as I drag the scrollbar button up and down the height of the button varies from about 1/4" to about 6" (the whole window is about 8" high).

An additional effect is that when you drag the scrollbar button down, you expect the viewport display to scroll up. Over part of the range that is what happens, but over part of the range the reverse occurs (dragging the button down also causes the display to move down).

Again, all this appears to result from incorrect calculations of the fraction of the table that is currently in view.

**Comment by dlemmermann** [comment]
I believe this has been fixed in JavaFX 17. Not sure about backport status.

**Comment by Maxoudela** [comment]
I have indeed observed what you described. The issue lay inside the VirtualFlow of JavaFX so there is not much we can do.
I'll check if we reproduce it on JavaFX 17. 
Otherwise I suggest opening a ticket on OpenJFX.

**Comment by jcschatzman** [comment]
Yes!  I tried the Early Access version of JavaFX (version 17). That fixes the jumping scrollbar problem. BIG improvement. Thanks for that tip!!

What it doesn't fix is the odd failure to scroll the entire viewport. 

In the current table I am looking at, when I first start to scroll down, the table background (white/grey boxes and borders) scroll smoothly and correctly. However the text from the 1st 3 rows does not scroll. So the text from the 4th row ends up on top of the text from the 3rd row, etc. Once I scroll 3 rows down, the text from rows 1-3, which hasn't scrolled at all, suddenly disappears.

I have attached some screenshots to attempt to explain the problem. Scroll0-5 are screenshots of the scroller window as I gradually slide the scrollbar down.
scroll0 - initial position at top - good
scroll1-4 - intermediate positions showing that part of the viewport gets scrolled and part does not - bad
scroll5 - scrolled the 1st 3 rows completed off the top - they disappear and everying this good
![scroll0](https://user-images.githubusercontent.com/86678509/123993981-2be3dd80-d98a-11eb-8811-b49e50747cf1.png)
![scroll1](https://user-images.githubusercontent.com/86678509/123993997-30a89180-d98a-11eb-95d3-c3c41fcbe2a5.png)
![scroll2](https://user-images.githubusercontent.com/86678509/123994005-330aeb80-d98a-11eb-8519-93527eede0be.png)
![scroll3](https://user-images.githubusercontent.com/86678509/123994012-356d4580-d98a-11eb-8c12-6aa4571b599e.png)
![scroll4](https://user-images.githubusercontent.com/86678509/123994018-37370900-d98a-11eb-9927-4b078c169673.png)
![scroll5](https://user-images.githubusercontent.com/86678509/123994034-3900cc80-d98a-11eb-91b6-b961a54dc46f.png)


I see that I now have 2 scrollbars, which I guess could have something to do with this, although the behavior just seems wrong. I will work on getting rid of the extra scrollbar to see if that resolves the remaining problem.

**Comment by jcschatzman** [comment]
Update: Removing the superfluous ScrollPane does not fix the "first three rows don't scroll" problem.

I have no "fixed" rows, other than the column headers. So the entire table should be scrolling. The user especially doesn't want to see part of the table scrolled on top of another part.

I have another example where the scrollbar can be scrolled all the way to the bottom and the first 3 rows remain the whole way. So the display is only correct when the scrollbar button is all the way at the top. More info: behavior is not affected by selection, by the fraction of the pane that is visible in the viewport (as long as it is <100%),  or by anything else I have thought of to try. I also can't figure out why it is the first 3 rows that don't scroll.


I observed this behavior with both JavaFX 16 and 17, but with JavaFX 16 it seemed to be only an occasional thing. With JavaFX 17, the behavior occurs 100% of the time.

**Comment by Maxoudela** [comment]
Do you have an [SSCCE](http://sscce.org/) to provide so that we can investigate? Is this happening on the SpreadsheetView? TableView? TableView2? All of them?

**Comment by FandangoL** [comment]
I have a similar bevaviour on SpreadsheetView with some fixed merged rows on header.
The header rows has a text spanning on more rows but such rows are merged so that there is enough room to fit the text.
Upon scrolling the merged cells of the header creates a white box that covers the scrolling rows as in the following image (I covered cell texts)
<img width="854" height="119" alt="Image" src="https://github.com/user-attachments/assets/07f9daac-4405-435a-9b0d-8fa097737fd5" />
In order to make the whole thing work I forced all rows of same height.
I added the following code to my contructor (my class inherits from SpreadsheetView):
        if (grid instanceof org.controlsfx.control.spreadsheet.GridBase) {
            org.controlsfx.control.spreadsheet.GridBase gridBase = (org.controlsfx.control.spreadsheet.GridBase) grid;

            gridBase.setRowHeightCallback(new javafx.util.Callback<Integer, Double>() {
                @Override
                public Double call(Integer rowIndex) {
                    return 24.0;
                }
            });
        }
Moreover if I programmatically perform a ctrl.scrollToRow(row) the visibility of the row is completely random as often is under the header.
